[build]
builder = "DOCKERFILE"

[deploy]
# 🚀 DEPLOY OTIMIZADO PARA CLAUDIA SUPREMA
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --worker-class gthread --timeout 120 --max-requests 1000 --preload backend.app:app"

# ⚡ VARIÁVEIS OTIMIZADAS PARA RAILWAY
[variables]
FLASK_ENV = "production"
ENABLE_EMOTIONAL_INTELLIGENCE = "true"
ENABLE_MEMORY_SYSTEM = "true"
ENABLE_SEMANTIC_ANALYSIS = "true"  
ENABLE_CONTINUOUS_LEARNING = "true"
BATCH_PROCESSING = "false"
ASYNC_PROCESSING = "true"
CACHE_EMBEDDINGS = "false"
MODEL_DEVICE = "cpu"
LOG_LEVEL = "INFO"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
restartPolicyMaxRetries = 10

[env]
PYTHON_VERSION = "3.11"
PORT = "8000"
FLASK_ENV = "production"
LOG_LEVEL = "INFO"

[services.web]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 300 backend.app:app"
healthcheckPath = "/health"

[services.web.env]
WEB_CONCURRENCY = "4"
MAX_WORKERS = "4"
